version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=anonygate
      - POSTGRES_PASSWORD=anonygate_pass
      - POSTGRES_DB=anonygate_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass anonygate_pass
    ports:
      - "6379:6379"

volumes:
  postgres_data:
