# Project identification
sonar.projectKey=g4-UCE-AnonyGate

# Sources (basado en el ls previo)
sonar.sources=apps,packages,infra

# Exclusiones
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/.turbo/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts,**/__tests__/**

# Reportes de cobertura (buscando recursivamente en todos los microservicios)
sonar.javascript.lcov.reportPaths=**/coverage/lcov.info
