name: CD Microservices (Docker & Deploy)

on:
  workflow_dispatch:
  push:
    branches: [ "QA", "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: ${{ github.actor }}/anonygate

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        service: [ms-auth, ms-alias]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/${{ matrix.service }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-${{ matrix.service }}:latest
          no-cache: true

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'qa' }}
    steps:
      - name: Deploy Microservices via Bastion
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_MS_CORE }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          proxy_host: ${{ secrets.EC2_HOST_NGINX }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Waiting for cloud-init to finish..."
            while [ ! -f /var/lib/cloud/instance/boot-finished ]; do sleep 5; done
            
            if ! command -v docker &> /dev/null; then
              echo "Docker not found! Forcing installation..."
              sudo apt-get update
              sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io docker-compose
            fi
            
            echo "${{ secrets.GITHUB_TOKEN }}" | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Create isolated env file for Microservices
            echo "DATABASE_URL_AUTH=\"postgresql://anonygate:anonygate_pass@${{ secrets.DB_POSTGRES_IP }}:5432/anonygate_db?schema=public\"" > .env
            echo "DATABASE_URL_ALIAS=\"postgresql://anonygate:anonygate_pass@${{ secrets.DB_POSTGRES_IP }}:5432/anonygate_db?schema=alias\"" >> .env
            echo "JWT_SECRET=\"SECRET_SUPER_SAFE_2026\"" >> .env
            echo "REDIS_HOST=\"${{ secrets.DB_QUEUES_IP }}\"" >> .env
            echo "REDIS_PORT=\"6379\"" >> .env
            
            # Pull new images
            sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-ms-auth:latest
            sudo docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-ms-alias:latest
            
            # Restart MS-Auth
            sudo docker stop ms-auth || true
            sudo docker rm ms-auth || true
            sudo docker run -d --name ms-auth -p 3000:3000 --env-file .env -e DATABASE_URL="postgresql://anonygate:anonygate_pass@${{ secrets.DB_POSTGRES_IP }}:5432/anonygate_db?schema=public" --restart unless-stopped ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-ms-auth:latest
            
            # Restart MS-Alias
            sudo docker stop ms-alias || true
            sudo docker rm ms-alias || true
            sudo docker run -d --name ms-alias -p 3001:3001 --env-file .env -e DATABASE_URL="postgresql://anonygate:anonygate_pass@${{ secrets.DB_POSTGRES_IP }}:5432/anonygate_db?schema=alias" --restart unless-stopped ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}-ms-alias:latest
