name: CD Terraform

on:
  push:
    branches: [ "main", "qa", "dev" ]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Environment (DEV)
        if: github.ref == 'refs/heads/dev'
        run: echo "TF_ENV=dev" >> $GITHUB_ENV
        
      - name: Set Environment (QA)
        if: github.ref == 'refs/heads/qa'
        run: echo "TF_ENV=qa" >> $GITHUB_ENV
        
      - name: Set Environment (PROD)
        if: github.ref == 'refs/heads/main'
        run: echo "TF_ENV=prod" >> $GITHUB_ENV
        
      - name: Terraform Init
        run: |
          cd infra/terraform/environments/${{ env.TF_ENV }}
          terraform init
          
      - name: Terraform Apply
        run: |
          cd infra/terraform/environments/${{ env.TF_ENV }}
          terraform apply -auto-approve
