name: CD Terraform

on:
  push:
    branches: [ "main", "QA" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Environment variables
        run: |
          if [ "${{ github.ref }}" == "refs/heads/QA" ]; then
            echo "TF_ENV=qa" >> $GITHUB_ENV
            echo "ENV_SUFFIX=_QA" >> $GITHUB_ENV
          else
            echo "TF_ENV=prod" >> $GITHUB_ENV
            echo "ENV_SUFFIX=_PROD" >> $GITHUB_ENV
          fi
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID{0}', env.ENV_SUFFIX)] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY{0}', env.ENV_SUFFIX)] }}
          aws-session-token: ${{ secrets[format('AWS_SESSION_TOKEN{0}', env.ENV_SUFFIX)] }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra/terraform/environments/${{ env.TF_ENV }}
          terraform init
          
      - name: Terraform Apply
        run: |
          cd infra/terraform/environments/${{ env.TF_ENV }}
          terraform apply -auto-approve
