name: CI Backend (NestJS, Python, Go)

on:
  push:
    branches: [ "main", "qa" ]
  pull_request:
    branches: [ "main", "qa" ]

jobs:
  build-and-test:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: npm install

      - name: Turbo Build
        run: npx turbo run build --filter="ms-*"

      - name: Turbo Test
        run: npx turbo run test --filter="ms-*"
