name: Debug EC2
on:
  push:
    branches: [ "QA" ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check Docker Logs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DB_POSTGRES_IP_QA }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_QA }}
          proxy_host: ${{ secrets.EC2_HOST_NGINX_QA }}
          proxy_username: ubuntu
          proxy_key: ${{ secrets.EC2_SSH_KEY_QA }}
          script: |
            echo "--- DOCKER PS DB ---"
            sudo docker ps -a
            echo "--- POSTGRES LOGS ---"
            sudo docker logs postgres --tail 50
